--뷰 이름은 자유
--1) 학생의 학점 4.5 만점으로 환산된 정보를 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW FORSTU(SNAME, MAJOR, AVR)
AS(
SELECT SNAME, MAJOR, ROUND((AVR*1.125),2)
FROM STUDENT);

SELECT *
    FROM FORSTU;

--2) 각 과목별 평균 점수를 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW AVGRE(MAJOR, RE)
AS(SELECT MAJOR, ROUND(AVG(RESULT), 2) AS RE
FROM STUDENT JOIN SCORE S2 
ON STUDENT.SNO = S2.SNO
GROUP BY MAJOR);

SELECT *
FROM AVGRE;

--3) 각 사원과 관리자의 이름을 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW EMP_MGR_VIEW(ENO, ENAME, MGRNAME)
AS
(
SELECT A.ENO, A.ENAME, E.ENAME
FROM EMP E
         RIGHT JOIN(SELECT ENO, ENAME, MGR FROM EMP) A
             ON A.MGR = E.ENO
    );
    
SELECT *
    FROM EMP_MGR_VIEW;

--4) 각 과목별 기말고사 평가 등급(A~F)까지와 해당 학생 정보를 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW GRMA(SNO, SNAME, MAJOR, RESULT, GRADE)
AS
(SELECT S2.SNO, SNAME, MAJOR, RESULT, GRADE
FROM SCGRADE, STUDENT JOIN  SCORE S2 ON STUDENT.SNO = S2.SNO
WHERE RESULT BETWEEN LOSCORE AND HISCORE
);

SELECT *
    FROM GRMA;

--5) 물리학과 교수의 과목을 수강하는 학생의 명단을 검색할 뷰를 생성하세요.
CREATE OR REPLACE VIEW MUL(SNAME, SECTION, PNAME)
AS
(
SELECT SNAME, SECTION, PNAME
FROM STUDENT
    JOIN SCORE S2 ON STUDENT.SNO = S2.SNO
    JOIN COURSE C2 ON S2.SNO = C2.CNO
    JOIN PROFESSOR P ON C2.PNO = P.PNO
    WHERE SECTION = '물리'
    );
    
SELECT * 
    FROM MUL;
    