--1) 4.5 환산 평점이 가장 높은 3인의 학생을 검색하세요.
SELECT ROWNUM, A.SNAME, A.RES
FROM ( SELECT SNAME, ROUND(AVG(AVR*1.125), 2) AS RES
        FROM STUDENT
        GROUP BY SNAME
        ORDER BY RES DESC
    ) A
    WHERE ROWNUM <= 3;

--2) 기말고사 과목별 평균이 높은 3과목을 검색하세요.
SELECT ROWNUM, A.MAJOR, A.RES
FROM (
SELECT MAJOR, ROUND(AVG(RESULT), 2) AS RES
FROM STUDENT 
    JOIN SCORE S2 ON STUDENT.SNO = S2.SNO
    GROUP BY MAJOR
    ORDER BY RES DESC) A
    WHERE ROWNUM <=3;
    
--3) 학과별, 학년별, 기말고사 평균이 순위 3까지를 검색하세요.(학과, 학년, 평균점수 검색)
SELECT ROWNUM, A.MAJOR, A.SYEAR, A.RES
FROM (SELECT SYEAR, MAJOR, ROUND(AVG(RESULT), 2) AS RES
    FROM STUDENT
        JOIN SCORE S2 ON STUDENT.SNO = S2.SNO
    GROUP BY MAJOR, SYEAR
    ORDER BY RES DESC) A
    WHERE ROWNUM <= 3;

--4) 기말고사 성적이 높은 과목을 담당하는 교수 3인을 검색하세요.(교수이름, 과목명, 평균점수 검색)
SELECT ROWNUM, A.PNAME, A.CNAME, A.RES
FROM (SELECT PNAME, CNAME, ROUND(AVG(RESULT), 2) AS RES
    FROM PROFESSOR P
    JOIN COURSE C2 
    ON P.PNO = C2.PNO
    JOIN SCORE S2 
    ON C2.CNO = S2.CNO
    GROUP BY PNAME, CNAME
    ORDER BY RES DESC) A
    WHERE ROWNUM <= 3;

--5) 교수별로 현재 수강중인 학생의 수를 검색하세요.
SELECT ROWNUM, SECTION, CO
FROM (SELECT SECTION, COUNT(*) AS CO
    FROM PROFESSOR P
    JOIN COURSE C2
    ON P.PNO = C2.PNO
    GROUP BY SECTION);
    